# Edit this Gemfile to bundle your application's dependencies.

source 'http://rubygems.org'

gem 'acts_as_list'
gem 'acts_as_state_machine'
gem 'acts_as_versioned', :git => 'https://github.com/technoweenie/acts_as_versioned'
gem 'authlogic'
gem 'builder'
gem 'exception_notification', :require => 'exception_notifier'
gem 'geokit'
gem 'geokit-rails3'
gem 'icalendar'
gem 'htmlentities'
gem 'memcache-client'
gem 'mysql2'
gem 'rails', '~>3.1.10'
gem 'RedCloth'
gem 'ruby-debug'
gem 'sanitize'
gem 'validates_email_format_of'
