#!/bin/bash
mysql -u root --password=borkborkbork -e "DROP DATABASE IF EXISTS ci_rails"
mysql -u root --password=borkborkbork -e "CREATE DATABASE ci_rails DEFAULT CHARACTER SET utf8"
mysql -u root --password=borkborkbork -e "GRANT ALL ON ci_rails.* TO 'ci_rails'@'localhost' IDENTIFIED BY 'hellnoiwontgowherethebuffaloroam'"
rake db:migrate
mysql -u root --password=borkborkbork ci_rails < initialize_db/country_names.sql
mysql -u root --password=borkborkbork ci_rails < initialize_db/us_states.sql
script/runner initialize_db/create_initial_accounts.rb
